In [18]:
import nltk
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
nltk.download("stopwords")
nltk.download('wordnet')
import spacy
import re
import matplotlib.pyplot as plt

[nltk_data] Downloading package stopwords to /home/ega/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/ega/nltk_data...

In [4]:
bbc_data = pd.read_csv("data/bbc_news.csv")
bbc_data

,Unnamed: 0,index,title,pubDate,guid,link,description
0,0,6684,Can I refuse to work?,"Wed, 10 Aug 2022 15:46:18 GMT",https://www.bbc.co.uk/news/business-62147992,https://www.bbc.co.uk/news/business-62147992?a...,With much of the UK enduring another period of...
1,1,9267,'Liz Truss the Brief?' World reacts to UK poli...,"Mon, 17 Oct 2022 11:35:12 GMT",https://www.bbc.co.uk/news/world-63285480,https://www.bbc.co.uk/news/world-63285480?at_m...,The UK's political chaos has been watched arou...
2,2,7387,Rationing energy is nothing new for off-grid c...,"Wed, 31 Aug 2022 05:20:18 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,Scoraig in the north west Highlands has long h...
3,3,767,The hunt for superyachts of sanctioned Russian...,"Tue, 22 Mar 2022 14:37:01 GMT",https://www.bbc.co.uk/news/60739336,https://www.bbc.co.uk/news/60739336?at_medium=...,"Wealthy Russians sanctioned by the US, EU and ..."
4,4,3712,Platinum Jubilee: 70 years of the Queen in 70 ...,"Wed, 01 Jun 2022 23:17:33 GMT",https://www.bbc.co.uk/news/uk-61660128,https://www.bbc.co.uk/news/uk-61660128?at_medi...,A quick look back at the Queen's 70 years on t...
...,...,...,...,...,...,...,...
995,995,13238,Dominic Raab: Third senior civil servant gives...,"Tue, 31 Jan 2023 22:39:11 GMT",https://www.bbc.co.uk/news/uk-politics-64470946,https://www.bbc.co.uk/news/uk-politics-6447094...,Deputy Prime Minister Dominic Raab is under in...
996,996,4730,Highlights: Radacanu beats Uytvanck,"Mon, 27 Jun 2022 17:54:28 GMT",https://www.bbc.co.uk/sport/av/tennis/61959705,https://www.bbc.co.uk/sport/av/tennis/61959705...,Watch US Open champion Emma Radacanu's best mo...
997,997,1871,In pictures: Mountain bikers descend snowy peak,"Sun, 17 Apr 2022 12:38:50 GMT",https://www.bbc.co.uk/news/uk-scotland-highlan...,https://www.bbc.co.uk/news/uk-scotland-highlan...,About 300 daring riders made an Easter weekend...
998,998,4346,"Companies must help cut living costs, says new...","Sat, 18 Jun 2022 02:15:07 GMT",https://www.bbc.co.uk/news/uk-politics-61842136,https://www.bbc.co.uk/news/uk-politics-6184213...,The government's new cost of living tsar says ...
999,999,8482,"Beware online car sale scams, consumers warned","Thu, 29 Sep 2022 00:06:47 GMT",https://www.bbc.co.uk/news/uk-63047193,https://www.bbc.co.uk/news/uk-63047193?at_medi...,A fake car dealership website defrauded victim...

In [5]:
bbc_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   1000 non-null   int64
 1   index        1000 non-null   int64
 2   title        1000 non-null   object
 3   pubDate      1000 non-null   object
 4   guid         1000 non-null   object
 5   link         1000 non-null   object
 6   description  1000 non-null   object
dtypes: int64(2), object(5)
memory usage: 54.8+ KB

In [6]:
titles = pd.DataFrame(bbc_data['title'])

In [7]:
titles.head()

                                               title
0                              Can I refuse to work?
1  'Liz Truss the Brief?' World reacts to UK poli...
2  Rationing energy is nothing new for off-grid c...
3  The hunt for superyachts of sanctioned Russian...
4  Platinum Jubilee: 70 years of the Queen in 70 ...

In [8]:
titles['lowercase'] = titles['title'].str.lower()
titles.head()

,title,lowercase
0,Can I refuse to work?,can i refuse to work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...

In [12]:
en_stopwords = stopwords.words("english")
titles['no_stopwords'] = titles['lowercase'].apply(lambda x : ' '.join([word for word in x.split() if word not in (en_stopwords)]))
titles.head()

,title,lowercase,no_stopwords
0,Can I refuse to work?,can i refuse to work?,refuse work?
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds

In [14]:
titles['no_stopwords_no_punct'] = titles.apply(lambda x : re.sub(r"([^\w\s])" , "" , x['no_stopwords']) , axis=1)
titles.head()

,title,lowercase,no_stopwords,no_stopwords_no_punct
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds

In [16]:
titles['token_raw'] = titles.apply(lambda x : word_tokenize(x['title']) , axis=1)
titles['token_clean'] = titles.apply(lambda x : word_tokenize(x['no_stopwords_no_punct']) , axis=1)
titles.head()

,title,lowercase,no_stopwords,no_stopwords_no_punct,token_raw,token_clean
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[The, hunt, for, superyachts, of, sanctioned, ...","[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[Platinum, Jubilee, :, 70, years, of, the, Que...","[platinum, jubilee, 70, years, queen, 70, seco..."

In [19]:
lemmatizer = WordNetLemmatizer()
titles['token_clean_lemmazited'] = titles['token_clean'].apply(lambda tokens : [lemmatizer.lemmatize(token) for token in tokens])
titles.head()

,title,lowercase,no_stopwords,no_stopwords_no_punct,token_raw,token_clean,token_clean_lemmazited
0,Can I refuse to work?,can i refuse to work?,refuse work?,refuse work,"[Can, I, refuse, to, work, ?]","[refuse, work]","[refuse, work]"
1,'Liz Truss the Brief?' World reacts to UK poli...,'liz truss the brief?' world reacts to uk poli...,'liz truss brief?' world reacts uk political t...,liz truss brief world reacts uk political turmoil,"['Liz, Truss, the, Brief, ?, ', World, reacts,...","[liz, truss, brief, world, reacts, uk, politic...","[liz, truss, brief, world, reacts, uk, politic..."
2,Rationing energy is nothing new for off-grid c...,rationing energy is nothing new for off-grid c...,rationing energy nothing new off-grid community,rationing energy nothing new offgrid community,"[Rationing, energy, is, nothing, new, for, off...","[rationing, energy, nothing, new, offgrid, com...","[rationing, energy, nothing, new, offgrid, com..."
3,The hunt for superyachts of sanctioned Russian...,the hunt for superyachts of sanctioned russian...,hunt superyachts sanctioned russian oligarchs,hunt superyachts sanctioned russian oligarchs,"[The, hunt, for, superyachts, of, sanctioned, ...","[hunt, superyachts, sanctioned, russian, oliga...","[hunt, superyachts, sanctioned, russian, oliga..."
4,Platinum Jubilee: 70 years of the Queen in 70 ...,platinum jubilee: 70 years of the queen in 70 ...,platinum jubilee: 70 years queen 70 seconds,platinum jubilee 70 years queen 70 seconds,"[Platinum, Jubilee, :, 70, years, of, the, Que...","[platinum, jubilee, 70, years, queen, 70, seco...","[platinum, jubilee, 70, year, queen, 70, second]"

In [21]:
token_raw_list = sum(titles['token_raw'] , [])
token_clean_list = sum(titles['token_clean_lemmazited'] , [])
token_raw_list

['Can',
 'I',
 'refuse',
 'to',
 'work',
 '?',
 "'Liz",
 'Truss',
 'the',
 'Brief',
 '?',
 "'",
 'World',
 'reacts',
 'to',
 'UK',
 'political',
 'turmoil',
 'Rationing',
 'energy',
 'is',
 'nothing',
 'new',
 'for',
 'off-grid',
 'community',
 'The',
 'hunt',
 'for',
 'superyachts',
 'of',
 'sanctioned',
 'Russian',
 'oligarchs',
 'Platinum',
 'Jubilee',
 ':',
 '70',
 'years',
 'of',
 'the',
 'Queen',
 'in',
 '70',
 'seconds',
 'Red',
 'Bull',
 'found',
 'guilty',
 'of',
 'breaking',
 'Formula',
 '1',
 "'s",
 'budget',
 'cap',
 'World',
 'Triathlon',
 'Championship',
 'Series',
 ':',
 'Flora',
 'Duffy',
 'beats',
 'Georgia',
 'Taylor-Brown',
 'to',
 'women',
 "'s",
 'title',
 'Terry',
 'Hall',
 ':',
 'Coventry',
 'scooter',
 'ride-out',
 'pays',
 'tribute',
 'to',
 'singer',
 'Post',
 'Office',
 'and',
 'Fujitsu',
 'to',
 'face',
 'inquiry',
 'over',
 'Horizon',
 'scandal',
 "'Pavement",
 'parking',
 'frightens',
 'me',
 "'",
 'UK',
 'interest',
 'rates',
 ':',
 'How',
 'will',
 'the',
 'rise',
 'affect',
 'you',
 'and',
 'how',
 'high',
 'could',
 'it',
 'go',
 '?',
 'They',
 'stayed',
 'for',
 'the',
 'storm',
 '-',
 'what',
 'happens',
 'now',
 '?',
 'Six',
 'Nations',
 ':',
 'Can',
 'Scotland',
 "'s",
 'best',
 'since',
 "'99",
 'beat',
 'best',
 'Ireland',
 'ever',
 '?',
 'How',
 'long',
 'can',
 'Liz',
 'Truss',
 'survive',
 'as',
 'prime',
 'minister',
 '?',
 'Platinum',
 'Jubilee',
 ':',
 'Beacons',
 'light',
 'across',
 'the',
 'globe',
 'to',
 'celebrate',
 'Queen',
 "'s",
 'reign',
 'Top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 'by',
 '5',
 '%',
 'in',
 'England',
 'Russians',
 'said',
 'they',
 '’',
 'd',
 'take',
 'my',
 'baby',
 ':',
 'A',
 'medic',
 '’',
 's',
 'story',
 'Week',
 'in',
 'pictures',
 ':',
 '11-17',
 'June',
 '2022',
 'Xi',
 'Jinping',
 'in',
 'Hong',
 'Kong',
 ':',
 'Tight',
 'security',
 'as',
 'city',
 'marks',
 '25',
 'years',
 'of',
 'handover',
 'Rescues',
 'carried',
 'out',
 'in',
 'silence',
 'to',
 'listen',
 'for',
 'sounds',
 'of',
 'life',
 'Nick',
 'Pope',
 ':',
 'Newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'How',
 'China',
 'plans',
 'to',
 'become',
 'the',
 'next',
 'big',
 'space',
 'power',
 'Barcelona',
 'thrash',
 'leaders',
 'Real',
 'Madrid',
 'in',
 'famous',
 'Clasico',
 'win',
 'Kuenssberg',
 ':',
 'The',
 'Budget',
 'can',
 'not',
 'mask',
 'big',
 'changes',
 'to',
 'our',
 'economy',
 'Nicola',
 'Bulley',
 'search',
 ':',
 'What',
 'we',
 'know',
 'about',
 'her',
 'disappearance',
 'Cost',
 'of',
 'living',
 ':',
 'Can',
 'Christmas',
 'lights',
 'displays',
 'survive',
 'the',
 'energy',
 'crisis',
 '?',
 'The',
 '100-year-old',
 'Edinburgh',
 'man',
 'still',
 'working',
 'three',
 'days',
 'a',
 'week',
 'Freya',
 'the',
 '600kg',
 'walrus',
 'causes',
 'a',
 'stir',
 'in',
 'Norway',
 'How',
 'can',
 'I',
 'offer',
 'a',
 'UK',
 'home',
 'to',
 'Ukrainian',
 'refugees',
 '?',
 'Nicola',
 'Bulley',
 'search',
 ':',
 'Former',
 'police',
 'boss',
 'says',
 'criticism',
 'is',
 'unfair',
 'Don',
 'Bolduc',
 ':',
 'Democrats',
 'elevated',
 'this',
 'Republican',
 '.',
 'Will',
 'it',
 'backfire',
 '?',
 'Some',
 'strike',
 'action',
 'cancelled',
 'after',
 'the',
 'Queen',
 "'s",
 'death',
 'The',
 'neighbourhood',
 'leading',
 'a',
 'green',
 'energy',
 'revolution',
 'Men',
 "'s",
 'U17',
 'European',
 'Championship',
 ':',
 'Dutch',
 '17-year-old',
 'Isaac',
 'Babadi',
 'scores',
 'Panenka',
 'penalty',
 'Amtrak',
 'derailment',
 ':',
 'Three',
 'killed',
 'in',
 'Missouri',
 'after',
 'train',
 'hits',
 'truck',
 'Energy',
 'price',
 'cap',
 ':',
 'Rising',
 'bills',
 '-',
 'four',
 'discounts',
 'and',
 'payments',
 'that',
 'could',
 'help',
 'you',
 'Environment',
 ':',
 'Are',
 'mushroom',
 'boards',
 'the',
 'future',
 'of',
 'surfing',
 '?',
 'Flying',
 'boats',
 'and',
 'other',
 'tech',
 'for',
 'cleaner',
 'shipping',
 'Scottish',
 'football',
 'to',
 'ban',
 'heading',
 'the',
 'day',
 'before',
 'and',
 'after',
 'matches',
 'Chris',
 'Eubank',
 'Jr',
 'v',
 'Liam',
 'Smith',
 ':',
 'What',
 'next',
 'for',
 'boxing',
 'after',
 "'unacceptable",
 "'",
 'taunts',
 '?',
 'The',
 'town',
 'destroyed',
 'to',
 'make',
 'way',
 'for',
 'a',
 'whites-only',
 'suburb',
 'Ukraine',
 'war',
 ':',
 'A',
 'village',
 'celebrates',
 'Russian',
 'retreat',
 'Root',
 'hits',
 'ton',
 'as',
 'England',
 'take',
 'command',
 'against',
 'West',
 'Indies',
 'Heineken',
 'Champions',
 'Cup',
 ':',
 'Leicester',
 '16-6',
 'Edinburgh',
 '-',
 'Jasper',
 'Wiese',
 'try',
 'sends',
 'Tigers',
 'into',
 'last',
 'eight',
 'World',
 'Cup',
 '2022',
 ':',
 'Bellingham',
 ',',
 'Gakpo',
 ',',
 'Fernandez',
 'and',
 'other',
 'breakout',
 'stars',
 'Briton',
 'Jack',
 'Fenton',
 'killed',
 'in',
 'Greek',
 'helicopter',
 'accident',
 'Emotional',
 'Sue',
 'Barker',
 'gets',
 'Centre',
 'Court',
 'ovation',
 'Ukrainian',
 'skating',
 'sisters',
 'back',
 'to',
 "'doing",
 'what',
 'they',
 'love',
 "'",
 'England',
 'v',
 'India',
 ':',
 'Edgbaston',
 'officials',
 'investigate',
 'crowd',
 'racism',
 'at',
 'Test',
 'Newspaper',
 'headlines',
 ':',
 'Rwanda',
 'plan',
 "'will",
 'fail',
 "'",
 'and',
 "'SAS",
 'train',
 'Kyiv',
 'forces',
 "'",
 'My',
 'Name',
 'Is',
 'Leon',
 ':',
 'Sir',
 'Lenny',
 'Henry',
 'brings',
 "'moving",
 "'",
 'adoption',
 'story',
 'to',
 'screen',
 'Big',
 'Brother',
 'star',
 'Glyn',
 'Wise',
 'plans',
 'to',
 'be',
 'priest',
 'Ministers',
 'asleep',
 'at',
 'the',
 'wheel',
 'over',
 'dentist',
 'shortages',
 ',',
 'say',
 'Lib',
 'Dems',
 'Chris',
 'Kaba',
 ':',
 'Met',
 'suspends',
 'officer',
 'who',
 'shot',
 'dead',
 'unarmed',
 'man',
 'World',
 'Cup',
 '2022',
 ':',
 'What',
 'we',
 'learned',
 'from',
 'a',
 'group',
 'stage',
 'that',
 'saw',
 'record',
 'number',
 'of',
 'upsets',
 'James',
 'Webb',
 ':',
 'Nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'pictures',
 'Constitution',
 'Hill',
 ':',
 'Cheltenham',
 'Champion',
 'Hurdle',
 'winner',
 "'the",
 'horse',
 'of',
 'a',
 'generation',
 "'",
 'At',
 'least',
 'one',
 'victim',
 'could',
 'have',
 'survived',
 'arena',
 'bomb',
 '-',
 'inquiry',
 'Gareth',
 'Bale',
 ':',
 'Wales',
 'captain',
 'retires',
 'from',
 'football',
 'aged',
 '33',
 'Ukraine',
 'war',
 ':',
 'Silent',
 'streets',
 'in',
 'wiped',
 'out',
 'Donetsk',
 'town',
 'World',
 'Cup',
 '2022',
 ':',
 'Vittorio',
 'Pozzo',
 "'s",
 'legacy',
 'and',
 'a',
 'record',
 'that',
 'might',
 'finally',
 'be',
 'under',
 'threat',
 'Train',
 'strikes',
 ':',
 'Workers',
 'vote',
 'on',
 'further',
 'six',
 'months',
 'of',
 'walkouts',
 'Eidevall',
 "'100",
 '%',
 'sure',
 "'",
 'Arsenal',
 'will',
 'advance',
 'after',
 'first-leg',
 'draw',
 'Ukraine',
 'war',
 ':',
 'Returning',
 'to',
 'the',
 'place',
 'my',
 'father',
 'was',
 'killed',
 'Furniture',
 'firm',
 'Made',
 'collapse',
 ':',
 'Customers',
 'in',
 'the',
 'dark',
 'over',
 'refunds',
 'Widow',
 'of',
 'US',
 'Capitol',
 'riot',
 'officer',
 'on',
 "'stigma",
 "'",
 'of',
 'his',
 'death',
 'NHS',
 'reaches',
 'deal',
 'for',
 'life-saving',
 'breast-cancer',
 'drug',
 'Giant',
 'ceramic',
 'sculpture',
 'by',
 'Sandy',
 'Brown',
 'has',
 'been',
 'unveiled',
 'in',
 'Cornwall',
 'CEO',
 'Secrets',
 ':',
 'How',
 'one',
 'company',
 'attracts',
 'more',
 'men',
 'Boris',
 'Becker',
 ':',
 'How',
 'a',
 'tennis',
 'superstar',
 'crashed',
 'to',
 'earth',
 'Turkish',
 'mine',
 'explosion',
 'kills',
 '25',
 'and',
 'leaves',
 'dozens',
 'trapped',
 'Indian',
 'Wells',
 ':',
 'Andy',
 'Murray',
 ',',
 'Emma',
 'Raducanu',
 'and',
 'Jack',
 'Draper',
 'win',
 'to',
 'reach',
 'third',
 'round',
 'World',
 'Athletics',
 'Championships',
 ':',
 'GB',
 "'s",
 'Keely',
 'Hodgkinson',
 'narrowly',
 'misses',
 'out',
 'on',
 'gold',
 'in',
 'dramatic',
 '800m',
 'NHS',
 'crisis',
 ':',
 'The',
 'medics',
 'trying',
 'to',
 'fix',
 'the',
 'health',
 'service',
 'How',
 'did',
 'jet',
 'crash',
 'into',
 'a',
 'block',
 'of',
 'flats',
 'in',
 'Russia',
 '?',
 'Prince',
 'Harry',
 'and',
 'Meghan',
 ':',
 'Where',
 'do',
 'they',
 'get',
 'their',
 'money',
 '?',
 'Chelsea',
 '4-2',
 'Man',
 'Utd',
 ':',
 'Chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'WSL',
 'title',
 'Tory',
 'leadership',
 ':',
 'I',
 "'d",
 'rather',
 'lose',
 'doing',
 'right',
 'thing',
 ',',
 'says',
 'Sunak',
 'Omagh',
 'police',
 'shooting',
 ':',
 'Four',
 'men',
 'released',
 'over',
 'John',
 'Caldwell',
 'attack',
 'Northern',
 'Ireland',
 '1-0',
 'Italy',
 ':',
 'Sarah',
 'McFadden',
 'scores',
 'famous',
 'winner',
 'in',
 'Belfast',
 'Actress',
 'Clara',
 'Darcy',
 ':',
 'Why',
 'I',
 "'m",
 'starring',
 'in',
 'a',
 'play',
 'about',
 'my',
 'brain',
 'tumour',
 'Bridgerton',
 ':',
 'South',
 'Asian',
 'faces',
 'on',
 'TV',
 "'makes",
 'me',
 'happy',
 "'",
 'Prince',
 'Harry',
 'remembers',
 'Queen',
 'Elizabeth',
 'II',
 "'s",
 'infectious',
 'smile',
 'Millions',
 'to',
 'receive',
 'latest',
 'cost-of-living',
 'payment',
 'Joe',
 'Biden',
 'heads',
 'to',
 'Middle',
 'East',
 'amid',
 'faltering',
 'US',
 'sway',
 'NHS',
 ':',
 'Public',
 'satisfaction',
 'with',
 'health',
 'service',
 'drops',
 'to',
 'record',
 'low',
 'Why',
 'have',
 "n't",
 'we',
 'seen',
 'any',
 'major',
 'winter',
 'storms',
 '?',
 'The',
 'Papers',
 ':',
 'Lions',
 "'bare",
 'teeth',
 "'",
 'and',
 'Starmer',
 "'s",
 'migration',
 'policy',
 'Afghanistan',
 'pupils',
 'in',
 'fear',
 'after',
 'spate',
 'of',
 'Islamic',
 'State',
 'attacks',
 'Princess',
 'of',
 'Wales',
 'Kate',
 'pays',
 'tribute',
 'to',
 'Queen',
 'Elizabeth',
 'at',
 'carol',
 'service',
 'Emma',
 'Raducanu',
 ...]

In [22]:
token_clean_list

['refuse',
 'work',
 'liz',
 'truss',
 'brief',
 'world',
 'reacts',
 'uk',
 'political',
 'turmoil',
 'rationing',
 'energy',
 'nothing',
 'new',
 'offgrid',
 'community',
 'hunt',
 'superyachts',
 'sanctioned',
 'russian',
 'oligarch',
 'platinum',
 'jubilee',
 '70',
 'year',
 'queen',
 '70',
 'second',
 'red',
 'bull',
 'found',
 'guilty',
 'breaking',
 'formula',
 '1',
 'budget',
 'cap',
 'world',
 'triathlon',
 'championship',
 'series',
 'flora',
 'duffy',
 'beat',
 'georgia',
 'taylorbrown',
 'womens',
 'title',
 'terry',
 'hall',
 'coventry',
 'scooter',
 'rideout',
 'pay',
 'tribute',
 'singer',
 'post',
 'office',
 'fujitsu',
 'face',
 'inquiry',
 'horizon',
 'scandal',
 'pavement',
 'parking',
 'frightens',
 'me',
 'uk',
 'interest',
 'rate',
 'rise',
 'affect',
 'high',
 'could',
 'go',
 'stayed',
 'storm',
 'happens',
 'now',
 'six',
 'nation',
 'scotland',
 'best',
 'since',
 '99',
 'beat',
 'best',
 'ireland',
 'ever',
 'long',
 'liz',
 'truss',
 'survive',
 'prime',
 'minister',
 'platinum',
 'jubilee',
 'beacon',
 'light',
 'across',
 'globe',
 'celebrate',
 'queen',
 'reign',
 'top',
 'student',
 'loan',
 'interest',
 'rate',
 'cut',
 '5',
 'england',
 'russian',
 'said',
 'theyd',
 'take',
 'baby',
 'medic',
 'story',
 'week',
 'picture',
 '1117',
 'june',
 '2022',
 'xi',
 'jinping',
 'hong',
 'kong',
 'tight',
 'security',
 'city',
 'mark',
 '25',
 'year',
 'handover',
 'rescue',
 'carried',
 'silence',
 'listen',
 'sound',
 'life',
 'nick',
 'pope',
 'newcastle',
 'goalkeeper',
 'extends',
 'incredible',
 'clean',
 'sheet',
 'record',
 'china',
 'plan',
 'become',
 'next',
 'big',
 'space',
 'power',
 'barcelona',
 'thrash',
 'leader',
 'real',
 'madrid',
 'famous',
 'clasico',
 'win',
 'kuenssberg',
 'budget',
 'can',
 'not',
 'mask',
 'big',
 'change',
 'economy',
 'nicola',
 'bulley',
 'search',
 'know',
 'disappearance',
 'cost',
 'living',
 'christmas',
 'light',
 'display',
 'survive',
 'energy',
 'crisis',
 '100yearold',
 'edinburgh',
 'man',
 'still',
 'working',
 'three',
 'day',
 'week',
 'freya',
 '600kg',
 'walrus',
 'cause',
 'stir',
 'norway',
 'offer',
 'uk',
 'home',
 'ukrainian',
 'refugee',
 'nicola',
 'bulley',
 'search',
 'former',
 'police',
 'bos',
 'say',
 'criticism',
 'unfair',
 'bolduc',
 'democrat',
 'elevated',
 'republican',
 'backfire',
 'strike',
 'action',
 'cancelled',
 'queen',
 'death',
 'neighbourhood',
 'leading',
 'green',
 'energy',
 'revolution',
 'men',
 'u17',
 'european',
 'championship',
 'dutch',
 '17yearold',
 'isaac',
 'babadi',
 'score',
 'panenka',
 'penalty',
 'amtrak',
 'derailment',
 'three',
 'killed',
 'missouri',
 'train',
 'hit',
 'truck',
 'energy',
 'price',
 'cap',
 'rising',
 'bill',
 'four',
 'discount',
 'payment',
 'could',
 'help',
 'environment',
 'mushroom',
 'board',
 'future',
 'surfing',
 'flying',
 'boat',
 'tech',
 'cleaner',
 'shipping',
 'scottish',
 'football',
 'ban',
 'heading',
 'day',
 'match',
 'chris',
 'eubank',
 'jr',
 'v',
 'liam',
 'smith',
 'next',
 'boxing',
 'unacceptable',
 'taunt',
 'town',
 'destroyed',
 'make',
 'way',
 'whitesonly',
 'suburb',
 'ukraine',
 'war',
 'village',
 'celebrates',
 'russian',
 'retreat',
 'root',
 'hit',
 'ton',
 'england',
 'take',
 'command',
 'west',
 'indie',
 'heineken',
 'champion',
 'cup',
 'leicester',
 '166',
 'edinburgh',
 'jasper',
 'wiese',
 'try',
 'sends',
 'tiger',
 'last',
 'eight',
 'world',
 'cup',
 '2022',
 'bellingham',
 'gakpo',
 'fernandez',
 'breakout',
 'star',
 'briton',
 'jack',
 'fenton',
 'killed',
 'greek',
 'helicopter',
 'accident',
 'emotional',
 'sue',
 'barker',
 'get',
 'centre',
 'court',
 'ovation',
 'ukrainian',
 'skating',
 'sister',
 'back',
 'doing',
 'love',
 'england',
 'v',
 'india',
 'edgbaston',
 'official',
 'investigate',
 'crowd',
 'racism',
 'test',
 'newspaper',
 'headline',
 'rwanda',
 'plan',
 'will',
 'fail',
 'sa',
 'train',
 'kyiv',
 'force',
 'name',
 'leon',
 'sir',
 'lenny',
 'henry',
 'brings',
 'moving',
 'adoption',
 'story',
 'screen',
 'big',
 'brother',
 'star',
 'glyn',
 'wise',
 'plan',
 'priest',
 'minister',
 'asleep',
 'wheel',
 'dentist',
 'shortage',
 'say',
 'lib',
 'dems',
 'chris',
 'kaba',
 'met',
 'suspends',
 'officer',
 'shot',
 'dead',
 'unarmed',
 'man',
 'world',
 'cup',
 '2022',
 'learned',
 'group',
 'stage',
 'saw',
 'record',
 'number',
 'upset',
 'james',
 'webb',
 'nasa',
 'space',
 'telescope',
 'delivers',
 'spectacular',
 'picture',
 'constitution',
 'hill',
 'cheltenham',
 'champion',
 'hurdle',
 'winner',
 'the',
 'horse',
 'generation',
 'least',
 'one',
 'victim',
 'could',
 'survived',
 'arena',
 'bomb',
 'inquiry',
 'gareth',
 'bale',
 'wale',
 'captain',
 'retires',
 'football',
 'aged',
 '33',
 'ukraine',
 'war',
 'silent',
 'street',
 'wiped',
 'donetsk',
 'town',
 'world',
 'cup',
 '2022',
 'vittorio',
 'pozzos',
 'legacy',
 'record',
 'might',
 'finally',
 'threat',
 'train',
 'strike',
 'worker',
 'vote',
 'six',
 'month',
 'walkout',
 'eidevall',
 '100',
 'sure',
 'arsenal',
 'advance',
 'firstleg',
 'draw',
 'ukraine',
 'war',
 'returning',
 'place',
 'father',
 'killed',
 'furniture',
 'firm',
 'made',
 'collapse',
 'customer',
 'dark',
 'refund',
 'widow',
 'u',
 'capitol',
 'riot',
 'officer',
 'stigma',
 'death',
 'nh',
 'reach',
 'deal',
 'lifesaving',
 'breastcancer',
 'drug',
 'giant',
 'ceramic',
 'sculpture',
 'sandy',
 'brown',
 'unveiled',
 'cornwall',
 'ceo',
 'secret',
 'one',
 'company',
 'attracts',
 'men',
 'boris',
 'becker',
 'tennis',
 'superstar',
 'crashed',
 'earth',
 'turkish',
 'mine',
 'explosion',
 'kill',
 '25',
 'leaf',
 'dozen',
 'trapped',
 'indian',
 'well',
 'andy',
 'murray',
 'emma',
 'raducanu',
 'jack',
 'draper',
 'win',
 'reach',
 'third',
 'round',
 'world',
 'athletics',
 'championship',
 'gb',
 'keely',
 'hodgkinson',
 'narrowly',
 'miss',
 'gold',
 'dramatic',
 '800m',
 'nh',
 'crisis',
 'medic',
 'trying',
 'fix',
 'health',
 'service',
 'jet',
 'crash',
 'block',
 'flat',
 'russia',
 'prince',
 'harry',
 'meghan',
 'get',
 'money',
 'chelsea',
 '42',
 'man',
 'utd',
 'chelsea',
 'win',
 'historic',
 'third',
 'successive',
 'wsl',
 'title',
 'tory',
 'leadership',
 'id',
 'rather',
 'lose',
 'right',
 'thing',
 'say',
 'sunak',
 'omagh',
 'police',
 'shooting',
 'four',
 'men',
 'released',
 'john',
 'caldwell',
 'attack',
 'northern',
 'ireland',
 '10',
 'italy',
 'sarah',
 'mcfadden',
 'score',
 'famous',
 'winner',
 'belfast',
 'actress',
 'clara',
 'darcy',
 'im',
 'starring',
 'play',
 'brain',
 'tumour',
 'bridgerton',
 'south',
 'asian',
 'face',
 'tv',
 'make',
 'happy',
 'prince',
 'harry',
 'remembers',
 'queen',
 'elizabeth',
 'ii',
 'infectious',
 'smile',
 'million',
 'receive',
 'latest',
 'costofliving',
 'payment',
 'joe',
 'biden',
 'head',
 'middle',
 'east',
 'amid',
 'faltering',
 'u',
 'sway',
 'nh',
 'public',
 'satisfaction',
 'health',
 'service',
 'drop',
 'record',
 'low',
 'seen',
 'major',
 'winter',
 'storm',
 'paper',
 'lion',
 'bare',
 'teeth',
 'starmers',
 'migration',
 'policy',
 'afghanistan',
 'pupil',
 'fear',
 'spate',
 'islamic',
 'state',
 'attack',
 'princess',
 'wale',
 'kate',
 'pay',
 'tribute',
 'queen',
 'elizabeth',
 'carol',
 'service',
 'emma',
 'raducanu',
 'u',
 'open',
 'champion',
 'discusses',
 'tough',
 'split',
 'coach',
 'torben',
 'beltz',
 'oxford',
 'united',
 '03',
 'arsenal',
 'eddie',
 'nketiah',
 'score',
 'twice',
 'gunner',
 'progress',
 'ukraine',
 'roundup',
 'putin',
 'defends',
 'necessary',
 'invasion',
 'kyiv',
 'averts',
 'cyberattack',
 'ni',
 'protocol',
 'uk',
 'eu',
 'reach',
 'agreement',
 'trade',
 'data',
 'sharing',
 'super',
 'mario',
 'bros',
 'movie',
 'jack',
 'black',
 'rise',
 'game',
 'adaptation',
 'fourtime',
 'slam',
 'champion',
 'osaka',
 'announces',
 'pregnancy',
 'mcdonalds',
 'cocacola',
 'boycott',
 'call',
 'grow',
 'russia',
 'womens',
 'footballer',
 'year',
 'contender',
 'sam',
 'kerr',
 'war',
 'ukraine',
 'vladimir',
 'putin',
 'trained',
 'fighter',
 'africa',
 'ryanairs',
 'michael',
 'oleary',
 'want',
 'practical',
 'immigration',
 'approach',
 'i',
 'planned',
 'end',
 'life',
 '16',
 'im',
 'still',
 'here',
 'england',
 '14',
 'men',
 'whipped',
 'twickenham',
 'crowd',
 'stirring',
 'display',
 'open',
 'rory',
 'mcilroy',
 'viktor',
 'hovland',
 'share',
 'lead',
 'st',
 'andrew',
 'third',
 'round',
 'real',
 'madrid',
 '20',
 'eintracht',
 'frankfurt',
 'karim',
 'benzema',
 'score',
 '324th',
 'goal',
 'real',
 'super',
 'cup',
 'win',
 'paper',
 'boris',
 'dossier',
 'judge',
 'to',
 'back',
 'down',
 'rwanda',
 'queen',
 'pull',
 'attending',
 'commonwealth',
 'service',
 'mosque',
 'fire',
 'suspect',
 'arrested',
 'second',
 'attack',
 'world',
 'cup',
 '2022',
 'belgium',
 'drop',
 'love',
 'away',
 'shirt',
 'qatar',
 'uk',
 'living',
 'covid',
 'plan',
 'soho',
 'street',
 'turned',
 'new',
 'london',
 'art',
 'gallery',
 'paper',
 'cruise',
 'ship',
 'house',
 'migrant',
 'new',
 'nh',
 'cash',
 'pay',
 'gap',
 'boss',
 'staff',
 'widen',
 'think',
 'tank',
 'local',
 'election',
 'child',
 'urge',
 'action',
 'save',
 'wildlife',
 'climate',
 'change',
 'uk',
 'track',
 'meet',
 'target',
 'trump',
 'investigation',
 'empty',
 'folder',
 'marked',
 'classified',
 'found',
 'maralago',
 'jim',
 'ratcliffe',
 'man',
 'bidding',
 'man',
 'utd',
 'shropshire',
 'baby',
 'death',
 'parent',
 'whose',
 'life',
 'changed',
 'forever',
 'bus',
 'journey',
 'taken',
 'since',
 '2',
 'fare',
 'cap',
 'say',
 'watchdog',
 'mexico',
 'kidnapping',
 'twisted',
 'moral',
 'code',
 'explains',
 'cartel',
 'apology',
 'rail',
 'fare',
 'england',
 'rise',
 'inflation',
 'rate',
 'minister',
 'say',
 'taliban',
 'school',
 'uturn',
 'a',
 'devastating',
 'day',
 'afghan',
 'girl',
 'malala',
 'yousafzai',
 'met',
 'police',
 'next',
 'force',
 'casey',
 'review',
 'ukraine',
 'war',
 'kherson',
 'mariupol',
 'key',
 'russian',
 'success',
 'heineken',
 'champion',
 'cup',
 'premiership',
 'cap',
 'hinders',
 'english',
 'team',
 'alex',
 'sanderson',
 'ukraine',
 'war',
 'protester',
 'expose',
 'crack',
 'kremlin',
 'war',
 'message',
 'liz',
 'truss',
 'vow',
 'match',
 'ukraine',
 'military',
 'support',
 'politics',
 'return',
 'wale',
 'population',
 'hit',
 'new',
 'high',
 'growth',
 'lowest',
 'many',
 'ukrainian',
 'fled',
 'home',
 'gone',
 'deloitte',
 'report',
 'european',
 'football',
 'made',
 'significant',
 'recovery',
 'covid',
 'pandemic',
 'nigeria',
 'flood',
 'overwhelming',
 'disaster',
 'leaf',
 '600',
 'people',
 'dead',
 'wimbledon',
 'emma',
 'raducanu',
 'andy',
 'murray',
 'set',
 'centre',
 'court',
 'day',
 'one',
 ...]

In [26]:
!python -m install en_code_web_sm
# nlp = spacy.load('en_code_web_sm')

/home/ega/Documents/Reset/AI/Ai-Generative/venv/bin/python: No module named install